# ndarray多维数组

## ndarrays的创建

In [1]:
import numpy as np

In [2]:
#rand固定区间0.0 - 1.0
arr = np.random.rand(3, 4)
arr

array([[0.99972352, 0.77051851, 0.19479581, 0.52539055],
       [0.53097509, 0.07203948, 0.3069445 , 0.17776225],
       [0.67524158, 0.96501427, 0.90398988, 0.70919207]])

In [3]:
#randint()可以指定区间
arr=np.random.randint(3,5,size=(3,4))
arr

array([[4, 4, 3, 4],
       [3, 3, 3, 4],
       [4, 3, 3, 4]])

In [4]:
#uniform()可以指定区间
arr = np.random.uniform(4, 19, size=(3, 4))
arr

array([[ 4.1693945 , 11.19839915, 18.81550458,  9.4976463 ],
       [15.06694577, 17.66473942, 10.95073443, 15.57893048],
       [11.49221494, 15.822632  ,  9.35088755,  5.97604177]])

## ndarray的序列创建

1. np.array(collection)

In [5]:
#collection 为 序列型对象(list)、嵌套序列对象(list of list)。
list = range(10)
arr = np.array(list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
list_li = [range(10), range(10)]
arr = np.array(list_li)
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

2. np.zeros()

In [11]:
zeros_arr=np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. np.ones()

In [13]:
ones_arr=np.ones((3,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. np.empty()

In [14]:
empty_arr=np.empty((3,4))
print(empty_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


5. np.arange()和reshape()

In [18]:
arr=np.arange(10)
print(arr)
print(arr.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


6. np.arange() 和 random.shuffle()

In [23]:
arr=np.arange(15)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2 12  5  9  7  4 10 14  3  6 11  0 13  8]


# ndarray的数据类型

1. dtype参数

In [ ]:
# 指定数组的数据类型，类型名+位数，如float64, int32

2. astype方法

In [7]:
# 初始化3行4列数组，数据类型为float64
float_arr=np.zeros((3,4),dtype=np.float64)
print(float_arr)
print(float_arr.dtype)
# astype转换数据类型，将已有的数组的数据类型转换为int32
int_arr=float_arr.astype(np.int32)
print(int_arr)
print(int_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


# ndarray的矩阵运算

1. 矢量运算：相同大小的数组间运算应用在元素上

In [8]:
arr=np.arange(6).reshape(2,3)
print(arr)
#矩阵相加
print(arr+arr)
#矩阵相乘
print(arr*arr)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  4]
 [ 9 16 25]]


2. 矢量和标量运算："广播" - 将标量"广播"到各个元素

In [9]:
arr=np.arange(6).reshape(2,3)
print(arr/3.)
print(arr+12)

[[0.         0.33333333 0.66666667]
 [1.         1.33333333 1.66666667]]
[[12 13 14]
 [15 16 17]]


# ndarray的索引与切片

In [10]:
#一维数组
arr=np.arange(19)
print(arr[3:6])

[3 4 5]



arr[r1:r2, c1:c2]

arr[1,1] 等价 arr[1][1]

[:] 代表某个维度的数据

In [11]:
#多维数组
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[1:2,1:2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[5]]


3. 条件索引

In [12]:
data_arr=np.random.rand(3,3)
print(data_arr)
year_arr=np.array([[2000,2001,2002],
                [2003,2004,20005],
                [2006,2007,2008]])
year_2005=year_arr>=2005
print(year_2005,year_2005.dtype)

fitt_arr=data_arr[(year_arr<=2005)&(year_arr)%2==0]
print(fitt_arr)

[[0.243472   0.66340088 0.24234669]
 [0.76050578 0.33869252 0.50999035]
 [0.93916429 0.884982   0.19279273]]
[[False False False]
 [False False  True]
 [ True  True  True]] bool
[0.243472   0.24234669 0.33869252 0.50999035 0.93916429 0.884982
 0.19279273]


# ndarray的维数转换

In [ ]:
# 二维数组直接使用转换函数：transpose()

# 高维数组转换要指定维度编号参数 (0, 1, 2, …)，注意参数是元组

In [13]:
arr = np.random.randint(2,13,size=(3,4))    # 2x3 数组
print(arr)    
print(arr.transpose()) # 转换为 3x2 数组

[[10 10 11 10]
 [ 4  2  8  7]
 [ 6  6 12  6]]
[[10  4  6]
 [10  2  6]
 [11  8 12]
 [10  7  6]]


In [14]:
# 2x3x4 数组，2对应0，3对应1，4对应2
arr=np.random.randint(2,34,size=(2,3,4))
print(arr)
print(arr.transpose(1,2,0))

[[[ 4 15 33 19]
  [22  3 33 18]
  [12 20 31 23]]

 [[ 6 24 23 30]
  [21 30  8 24]
  [11  8  3 33]]]
[[[ 4  6]
  [15 24]
  [33 23]
  [19 30]]

 [[22 21]
  [ 3 30]
  [33  8]
  [18 24]]

 [[12 11]
  [20  8]
  [31  3]
  [23 33]]]


# 元素计算函数

In [ ]:
# 1. ceil(): 向上最接近的整数，参数是 number 或 array

# 2. floor(): 向下最接近的整数，参数是 number 或 array

# 3. rint(): 四舍五入，参数是 number 或 array

# 4. isnan(): 判断元素是否为 NaN(Not a Number)，参数是 number 或 array

# 5. multiply(): 元素相乘，参数是 number 或 array

# 6. divide(): 元素相除，参数是 number 或 array

# 7. abs()：元素的绝对值，参数是 number 或 array

# 8. where(condition, x, y): 三元运算符，x if condition else y

In [57]:
arr=np.random.randn(2,4)
print(arr)
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))
print(np.multiply(arr,arr))
print(np.divide(arr,arr))
print(np.abs(arr))
print(np.where(arr>0,1,2))

[[-1.93265313  1.75440552  0.02380325  1.1845227 ]
 [-0.37298304 -1.04514333  0.77486848  1.45904998]]
[[-1.  2.  1.  2.]
 [-0. -1.  1.  2.]]
[[-2.  1.  0.  1.]
 [-1. -2.  0.  1.]]
[[-2.  2.  0.  1.]
 [-0. -1.  1.  1.]]
[[False False False False]
 [False False False False]]
[[3.73514811e+00 3.07793872e+00 5.66594595e-04 1.40309402e+00]
 [1.39116348e-01 1.09232458e+00 6.00421155e-01 2.12882684e+00]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.93265313 1.75440552 0.02380325 1.1845227 ]
 [0.37298304 1.04514333 0.77486848 1.45904998]]
[[2 1 1 1]
 [2 2 1 1]]


# 元素统计函数

In [ ]:
# 1. np.mean(), np.sum()：所有元素的平均值，所有元素的和，参数是 number 或 array

# 2. np.max(), np.min()：所有元素的最大值，所有元素的最小值，参数是 number 或 array

# 3. np.std(), np.var()：所有元素的标准差，所有元素的方差，参数是 number 或 array

# 4. np.argmax(), np.argmin()：最大值的下标索引值，最小值的下标索引值，参数是 number 或 array

# 5. np.cumsum(), np.cumprod()：返回一个一维数组，每个元素都是之前所有元素的 累加和 和 累乘积，参数是 number 或 array

# 6. 多维数组默认统计全部维度，axis参数可以按指定轴心统计，值为0则按列统计，值为1则按行统计。

In [15]:
arr=np.arange(12).reshape(3,4)
np.random.shuffle(arr)
print(arr)
print(np.mean(arr,axis=1))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
[5.5 9.5 1.5]
66
11
0
3.452052529534663
11.916666666666666
7
8
[ 4  9 15 22 30 39 49 60 60 61 63 66]
[      4      20     120     840    6720   60480  604800 6652800       0
       0       0       0]


# 元素判断函数

In [ ]:
# 1. np.any(): 至少有一个元素满足指定条件，返回True
# 2. np.all(): 所有的元素满足指定条件，返回True

In [63]:
arr=np.random.randn(2,3)
print(arr)
print(np.any(arr>0))
print(np.all(arr>0))

[[ 0.61449432  2.15252619 -1.40056063]
 [-0.86659354  0.21893125  1.57005309]]
True
False


# 元素去重排序函数

In [ ]:
# np.unique():找到唯一值并返回排序结果，类似于Python的set集合

In [65]:
arr=np.arange(10).reshape(5,2)
np.random.shuffle(arr)
print(arr)
print(np.unique(arr))

[[2 3]
 [8 9]
 [6 7]
 [4 5]
 [0 1]]
[0 1 2 3 4 5 6 7 8 9]


# 求两个数组中元素相等的个数

In [2]:
import numpy as np

In [14]:
a=np.random.randint(0,2,20)
b=np.random.randint(0,2,20)
a,b

(array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0]),
 array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1]))

In [15]:
print(a == b)

[False  True  True  True False False  True  True  True False  True False
 False  True False  True False False  True False]


In [17]:
print(np.sum(a == b)/len(a))
print(np.sum(a == b))

0.5
10
