In [1]:
import numpy as np

# ndarray数组创建

## ndarrays的创建

In [2]:
import numpy as np

In [2]:
# rand固定区间0.0 - 1.0
arr = np.random.rand(3, 4)
arr

array([[0.99972352, 0.77051851, 0.19479581, 0.52539055],
       [0.53097509, 0.07203948, 0.3069445 , 0.17776225],
       [0.67524158, 0.96501427, 0.90398988, 0.70919207]])

In [3]:
# randint()可以指定区间
arr=np.random.randint(3,5,size=(3,4))
arr

array([[4, 4, 3, 4],
       [3, 3, 3, 4],
       [4, 3, 3, 4]])

In [4]:
# uniform()可以指定区间
arr = np.random.uniform(4, 19, size=(3, 4))
arr

array([[ 4.1693945 , 11.19839915, 18.81550458,  9.4976463 ],
       [15.06694577, 17.66473942, 10.95073443, 15.57893048],
       [11.49221494, 15.822632  ,  9.35088755,  5.97604177]])

## ndarray的序列创建

1. np.array(collection)

In [5]:
# collection 为 序列型对象(list)、嵌套序列对象(list of list)。
list = range(10)
arr = np.array(list)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
list_li = [range(10), range(10)]
arr = np.array(list_li)
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

2. np.zeros()

In [11]:
zeros_arr=np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. np.ones()

In [13]:
ones_arr=np.ones((3,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. np.empty()

In [14]:
empty_arr=np.empty((3,4))
print(empty_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


5. np.arange()和reshape()

In [18]:
arr=np.arange(10)
print(arr)
print(arr.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


6. np.arange() 和 random.shuffle()

In [23]:
arr=np.arange(15)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2 12  5  9  7  4 10 14  3  6 11  0 13  8]


7.linspace

In [33]:
# 产生 `N` 个等距分布在 `[start, stop]`间的元素组成的数组，包括 `start, stop`
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

8.logspace

In [34]:
# 产生 N 个对数等距分布的数组，默认以10为底：
np.logspace(0, 1, 5)

array([ 1.   ,  1.778,  3.162,  5.623, 10.   ])

9.meshgrid

In [35]:
# 在二维平面中生成一个网格，这时候可以使用 `meshgrid`
x_ticks = np.linspace(-1, 1, 5)
y_ticks = np.linspace(-1, 1, 5)
x, y = np.meshgrid(x_ticks, y_ticks)
display(x, y)

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

## 矩阵创建

In [37]:
# 1.使用 `mat` 方法将 `2` 维数组转化为矩阵：
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
display(A)

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [38]:
# 2.利用分块创造新的矩阵
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [39]:
# 3.矩阵与向量的乘法：
x = np.array([[1], [2], [3]])
display(A * x)

matrix([[17],
        [21],
        [50]])

In [40]:
# 4.`A.I` 表示 `A` 矩阵的逆矩阵：
display(A * A.I)

matrix([[1.000e+00, 0.000e+00, 1.388e-17],
        [0.000e+00, 1.000e+00, 6.939e-17],
        [0.000e+00, 0.000e+00, 1.000e+00]])

# ndarray的数据类型


|基本类型|可用的**Numpy**类型|备注
|--|--|--
|布尔型|`bool`|占1个字节
|整型|`int8, int16, int32, int64, int128, int`| `int` 跟**C**语言中的 `long` 一样大
|无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`| `uint` 跟**C**语言中的 `unsigned long` 一样大
|浮点数| `float16, float32, float64, float, longfloat`|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
|复数| `complex64, complex128, complex, longcomplex`| 默认为 `complex128` ，即实部虚部都为双精度
|字符串| `string, unicode` | 可以使用 `dtype=S4` 表示一个4字节字符串的数组
|对象| `object` |数组中可以使用任意值|
|Records| `void` ||
|时间| `datetime64, timedelta64` ||

1. dtype参数

In [ ]:
# 指定数组的数据类型，类型名+位数，如float64, int32

2. astype方法

In [3]:
# 1.初始化3行4列数组，数据类型为float64
float_arr = np.zeros((3,4),dtype=np.float64)
print(float_arr)
print(float_arr.dtype)
# astype转换数据类型，将已有的数组的数据类型转换为int32
int_arr = float_arr.astype(np.int32)
print(int_arr)
print(int_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [4]:
# 2.查看维数
float_arr.ndim

2

3.复数类型

In [4]:
# 1.创建
a = np.array([1 + 1j, 2, 3, 4])
display(a.dtype)

dtype('complex128')

In [5]:
# 2.实部和虚部
display(a.real, a.imag)

array([1., 2., 3., 4.])

array([1., 0., 0., 0.])

In [6]:
# 3.设置值
a.imag = [1,2,3,4]
display(a)

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [7]:
# 4.复共轭
display(a.conj())

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

4.view方法

In [9]:
# view方法共用一块内存
a = np.array((1,2,3,4), dtype=np.int32)
b = a.view(np.uint8)
display(a, b)

array([1, 2, 3, 4])

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

# ndarray的张量运算

1. 矢量运算

In [8]:
arr = np.arange(6).reshape(2,3)
print(arr)
# 矩阵相加
print(arr+arr)
# 矩阵相乘
print(arr*arr)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  4]
 [ 9 16 25]]


2. 矢量和标量运算

In [9]:
arr = np.arange(6).reshape(2,3)
print(arr/3.)
print(arr+12)

[[0.         0.33333333 0.66666667]
 [1.         1.33333333 1.66666667]]
[[12 13 14]
 [15 16 17]]


3.求和

In [12]:
a = np.array([[1,2,3], [4,5,6]])
display(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# 1.求所有元素和
display(np.sum(a), a.sum())

21

21

In [17]:
# 2.按维度求和
display(np.sum(a, axis=0), a.sum(axis = 0))

array([5, 7, 9])

array([5, 7, 9])

3.求积

In [2]:
a = np.array([[1,2,3], [4,5,6]])
display(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 1.所有元素
display(a.prod(), np.prod(a, axis=0))

720

array([ 4, 10, 18])

4.最大最小值

In [4]:
a = np.random.rand(3, 4)
%precision 3
display(a)

array([[0.685, 0.779, 0.99 , 0.932],
       [0.43 , 0.902, 0.605, 0.557],
       [0.429, 0.5  , 0.971, 0.097]])

In [5]:
# 1.最大最小值
display(a.min(), a.min(axis=1))
display(a.max(), a.max(axis=1))

0.09743819566246292

array([0.685, 0.43 , 0.097])

0.9903485703973168

array([0.99 , 0.902, 0.971])

In [6]:
# 2.最大最小值位置
display(a.argmin(), a.argmin(axis=0))

11

array([2, 2, 1, 2], dtype=int64)

## 张量四则运算

运算|函数
--- | --- 
`a + b` | `add(a,b)`
`a - b` | `subtract(a,b)`
`a * b` | `multiply(a,b)`
`a / b` | `divide(a,b)`
`a ** b` | `power(a,b)`
`a % b` | `remainder(a,b)`

In [41]:
# 1.乘法
a = np.array([1,2])
b = np.array([3,4])
display(np.multiply(a, b))

array([3, 8])

## 张量比较运算

运算|函数<
--- | --- 
`==` | `equal`
`!=` | `not_equal`
`>` | `greater`
`>=` | `greater_equal`
`<` | `less`
`<=` | `less_equal`
| `logical_and`
| `logical_or`
| `logical_xor`
| `logical_not`
`&` | `bitwise_and`
 | `bitwise_or`
`^` | `bitwise_xor`
`~` | `invert`
`>>` | `right_shift`
`<<` | `left_shift`

# ndarray的索引与切片

In [10]:
# 一维数组
arr = np.arange(19)
print(arr[3:6])

[3 4 5]



arr[r1:r2, c1:c2]

arr[1,1] 等价 arr[1][1]

[:] 代表某个维度的数据

In [11]:
# 多维数组
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr[1:2,1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[5]]


3. 条件索引

In [12]:
data_arr = np.random.rand(3,3)
print(data_arr)
year_arr = np.array([[2000,2001,2002],
                [2003,2004,20005],
                [2006,2007,2008]])
year_2005 = year_arr>=2005
print(year_2005,year_2005.dtype)

fitt_arr=data_arr[(year_arr<=2005)&(year_arr)%2==0]
print(fitt_arr)

[[0.243472   0.66340088 0.24234669]
 [0.76050578 0.33869252 0.50999035]
 [0.93916429 0.884982   0.19279273]]
[[False False False]
 [False False  True]
 [ True  True  True]] bool
[0.243472   0.24234669 0.33869252 0.50999035 0.93916429 0.884982
 0.19279273]


# 数组形状

In [18]:
# 1.修改数组形状
a = np.arange(6)
display(a.reshape(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
# 2.使用 newaxis 增加数组维数
a = np.arange(3)
y = a[np.newaxis, :]
display(y.shape)

y = a[np.newaxis, np.newaxis, :]
display(np.shape(y))

(1, 3)

(1, 1, 3)

In [21]:
# 3.squeeze 方法去除多余的轴
a =np.arange(6)
a.shape = (2,1,3)
b = a.squeeze()
display(b.shape)

(2, 3)

## ndarray的维数转换

In [ ]:
# 二维数组直接使用转换函数：transpose()

# 高维数组转换要指定维度编号参数 (0, 1, 2, …)，注意参数是元组

In [13]:
arr = np.random.randint(2,13,size=(3,4))    # 2x3 数组
print(arr)    
print(arr.transpose()) # 转换为 3x2 数组

[[10 10 11 10]
 [ 4  2  8  7]
 [ 6  6 12  6]]
[[10  4  6]
 [10  2  6]
 [11  8 12]
 [10  7  6]]


In [14]:
# 2x3x4 数组，2对应0，3对应1，4对应2
arr=np.random.randint(2,34,size=(2,3,4))
print(arr)
print(arr.transpose(1,2,0))

[[[ 4 15 33 19]
  [22  3 33 18]
  [12 20 31 23]]

 [[ 6 24 23 30]
  [21 30  8 24]
  [11  8  3 33]]]
[[[ 4  6]
  [15 24]
  [33 23]
  [19 30]]

 [[22 21]
  [ 3 30]
  [33  8]
  [18 24]]

 [[12 11]
  [20  8]
  [31  3]
  [23 33]]]


## 数组连接

1.concatenate函数

In [22]:
x = np.array([
        [0,1,2],
        [10,11,12]
    ])
y = np.array([
        [50,51,52],
        [60,61,62]
    ])

In [23]:
z = np.concatenate((x,y))
display(z.shape)

(4, 3)

## 展平数组

In [24]:
# 1.flatten方法
a = np.array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [25]:
# 2.ravel方法
a = np.array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

# 元素计算函数

In [ ]:
# 1. ceil(): 向上最接近的整数，参数是 number 或 array

# 2. floor(): 向下最接近的整数，参数是 number 或 array

# 3. rint(): 四舍五入，参数是 number 或 array

# 4. isnan(): 判断元素是否为 NaN(Not a Number)，参数是 number 或 array

# 5. multiply(): 元素相乘，参数是 number 或 array

# 6. divide(): 元素相除，参数是 number 或 array

# 7. abs()：元素的绝对值，参数是 number 或 array

# 8. where(condition, x, y): 三元运算符，x if condition else y

In [57]:
arr=np.random.randn(2,4)
print(arr)
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))
print(np.multiply(arr,arr))
print(np.divide(arr,arr))
print(np.abs(arr))
print(np.where(arr>0,1,2))

[[-1.93265313  1.75440552  0.02380325  1.1845227 ]
 [-0.37298304 -1.04514333  0.77486848  1.45904998]]
[[-1.  2.  1.  2.]
 [-0. -1.  1.  2.]]
[[-2.  1.  0.  1.]
 [-1. -2.  0.  1.]]
[[-2.  2.  0.  1.]
 [-0. -1.  1.  1.]]
[[False False False False]
 [False False False False]]
[[3.73514811e+00 3.07793872e+00 5.66594595e-04 1.40309402e+00]
 [1.39116348e-01 1.09232458e+00 6.00421155e-01 2.12882684e+00]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.93265313 1.75440552 0.02380325 1.1845227 ]
 [0.37298304 1.04514333 0.77486848 1.45904998]]
[[2 1 1 1]
 [2 2 1 1]]


# 元素统计函数

In [ ]:
# 1. np.mean(), np.sum()：所有元素的平均值，所有元素的和，参数是 number 或 array

# 2. np.max(), np.min()：所有元素的最大值，所有元素的最小值，参数是 number 或 array

# 3. np.std(), np.var()：所有元素的标准差，所有元素的方差，参数是 number 或 array

# 4. np.argmax(), np.argmin()：最大值的下标索引值，最小值的下标索引值，参数是 number 或 array

# 5. np.cumsum(), np.cumprod()：返回一个一维数组，每个元素都是之前所有元素的 累加和 和 累乘积，参数是 number 或 array

# 6. 多维数组默认统计全部维度，axis参数可以按指定轴心统计，值为0则按列统计，值为1则按行统计。

# 7. np.var(), 计算方差

# 8. np.rount(), 近似，默认到整数：a.round(decimals=1),近似到一位小数

In [15]:
arr=np.arange(12).reshape(3,4)
np.random.shuffle(arr)
print(arr)
print(np.mean(arr,axis=1))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
[5.5 9.5 1.5]
66
11
0
3.452052529534663
11.916666666666666
7
8
[ 4  9 15 22 30 39 49 60 60 61 63 66]
[      4      20     120     840    6720   60480  604800 6652800       0
       0       0       0]


## 对角线数据

In [30]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3

In [31]:
# 1.查看
a.diagonal()

array([11, 22, 33])

In [32]:
# 2.可以使用偏移来查看它的次对角线，正数表示右移，负数表示左移：
display(a.diagonal(offset=1))
display(a.diagonal(offset=-1))

array([21, 32])

array([12, 23])

# 元素判断函数

In [ ]:
# 1. np.any(): 至少有一个元素满足指定条件，返回True
# 2. np.all(): 所有的元素满足指定条件，返回True

In [63]:
arr=np.random.randn(2,3)
print(arr)
print(np.any(arr>0))
print(np.all(arr>0))

[[ 0.61449432  2.15252619 -1.40056063]
 [-0.86659354  0.21893125  1.57005309]]
True
False


# 元素其他函数

1.clip

In [7]:
# 将数值限制在某个范围：
arr = np.arange(10).reshape(5,2)
display(arr.clip(3,5))

array([[3, 3],
       [3, 3],
       [4, 5],
       [5, 5],
       [5, 5]])

2.ptp

In [8]:
# 计算最大值和最小值之差：
display(arr.ptp(axis=1))

array([1, 1, 1, 1, 1])

In [65]:
# np.unique():找到唯一值并返回排序结果，类似于Python的set集合
arr = np.arange(10).reshape(5,2)
np.random.shuffle(arr)
print(arr)
print(np.unique(arr))

[[2 3]
 [8 9]
 [6 7]
 [4 5]
 [0 1]]
[0 1 2 3 4 5 6 7 8 9]


# numpy中的其他操作

## 求两个数组中元素相等的个数

In [2]:
import numpy as np

In [14]:
a=np.random.randint(0,2,20)
b=np.random.randint(0,2,20)
a,b

(array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0]),
 array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1]))

In [15]:
print(a == b)

[False  True  True  True False False  True  True  True False  True False
 False  True False  True False False  True False]


In [17]:
print(np.sum(a == b)/len(a))
print(np.sum(a == b))

0.5
10


# 张量操作

## 排序

1.sort函数

In [10]:
# 返回从小到大
names = np.array(['bob', 'sue', 'jan', 'ad'])
weights = np.array([20.8, 93.2, 53.4, 61.8])

np.sort(weights)

array([20.8, 53.4, 61.8, 93.2])

2.argsort 函数

In [11]:
# argsort返回从小到大的排列在数组中的索引位置
ordered_indices = np.argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

In [12]:
# 可以用它来索引
display(weights[ordered_indices])

array([20.8, 53.4, 61.8, 93.2])

3.searchsorted 函数

In [13]:
# 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置
sorted_array = np.linspace(0,1,5)
values = np.array([.1,.8,.3,.12,.5,.25])
display(np.searchsorted(sorted_array, values))

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [14]:
data = np.random.rand(100)
data.sort()
bounds = (.4, .6)

In [16]:
# 返回这两个值对应的插入位置
low_idx, high_idx = np.searchsorted(data, bounds)
display(data[low_idx:high_idx])

array([0.417, 0.419, 0.419, 0.437, 0.469, 0.478, 0.487, 0.488, 0.489,
       0.495, 0.51 , 0.529, 0.533, 0.537, 0.541, 0.549, 0.552, 0.557,
       0.562, 0.563, 0.564, 0.581, 0.581, 0.582, 0.585])

# ufunc 对象

In [43]:
# `ufunc` 则是能够对数组进行处理的函数
# 1.查看支持的方法
a = np.array([0,1,2])
b = np.array([2,3,4])
display(dir(np.add))

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

## reduce 方法

In [44]:
# op.reduce(a)
# 将`op`沿着某个轴应用，使得数组 `a` 的维数降低一维。
a = np.array([1,2,3,4])
np.add.reduce(a)

10

In [45]:
# 1.多维
a = np.array([[1,2,3],[4,5,6]])
np.add.reduce(a)

array([5, 7, 9])

In [46]:
# 2.指定轴
np.add.reduce(a, 1)

array([ 6, 15])

In [47]:
# 3.逻辑运算
a = np.array([1,1,0,1])
np.logical_and.reduce(a)

False

## accumulate 

In [48]:
# op.accumulate(a)
# `accumulate` 可以看成保存 `reduce` 每一步的结果所形成的数组。
a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

## reduceat 

In [49]:
# op.reduceat(a, indices)
# `reduceat` 方法将操作符运用到指定的下标上，返回一个与 `indices` 大小相同的数组：
a = np.array([0, 10, 20, 30, 40, 50])
indices = np.array([1,4])

np.add.reduceat(a, indices)
# 这里，`indices` 为 `[1, 4]`，所以 `60` 表示从下标1（包括）加到下标4（不包括）的结果，`90` 表示从下标4（包括）加到结尾的结果。

array([60, 90], dtype=int32)

## outer

In [51]:
# op.outer(a, b)
# 对于 `a` 中每个元素，将 `op` 运用到它和 `b` 的每一个元素上所得到的结果：
a = np.array([0,1])
b = np.array([1,2,3])

np.add.outer(a, b)

array([[1, 2, 3],
       [2, 3, 4]])

# 文件读取和写入

## 读取文件

In [ ]:
# 1.读取空格分割的文本

In [53]:
%%writefile myfile.txt
2.1 2.3 3.2 1.3 3.1
6.1 3.1 4.2 2.3 1.8

Writing myfile.txt


In [54]:
data = np.loadtxt('myfile.txt')
data

array([[2.1, 2.3, 3.2, 1.3, 3.1],
       [6.1, 3.1, 4.2, 2.3, 1.8]])

In [55]:
# 2.逗号分割的文本

In [56]:
%%writefile myfile.txt
2.1, 2.3, 3.2, 1.3, 3.1
6.1, 3.1, 4.2, 2.3, 1.8

Overwriting myfile.txt


In [57]:
data = np.loadtxt('myfile.txt', delimiter=',')
data

array([[2.1, 2.3, 3.2, 1.3, 3.1],
       [6.1, 3.1, 4.2, 2.3, 1.8]])

## loadtxt函数

In [ ]:
# 1.loadtxt的使用

In [58]:
%%writefile myfile.txt
 -- BEGINNING OF THE FILE
% Day, Month, Year, Skip, Power
01, 01, 2000, x876, 13 % wow!
% we don't want have Jan 03rd
04, 01, 2000, xfed, 55

Overwriting myfile.txt


In [59]:
data = np.loadtxt('myfile.txt', 
                  skiprows=1,         #忽略第一行
                  dtype=np.int,      #数组类型
                  delimiter=',',     #逗号分割
                  usecols=(0,1,2,4), #指定使用哪几列数据
                  comments='%'       #百分号为注释符
                 )
data

C:\Users\17677\AppData\Local\Temp\ipykernel_15284\2657762018.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int,      #数组类型


array([[   1,    1, 2000,   13],
       [   4,    1, 2000,   55]])

## 写入文件

In [65]:
# 1.将数组写入文件
# `savetxt` 可以将数组写入文件，默认使用科学计数法的形式保存：
data = np.array([[1,2], 
                 [3,4]])
np.savetxt('test100.txt', data)

In [66]:
## 以整数保存
data = np.array([[1,2], 
                 [3,4]])

np.savetxt('out.txt', data, fmt="%d") #保存为整数

In [67]:
## 以整数保存，逗号作为分隔符
data = np.array([[1,2], 
                 [3,4]])

np.savetxt('out.txt', data, fmt="%.2f", delimiter=',') #保存为2位小数的浮点数，用逗号分隔

In [68]:
# 2.二进制格式保存
# 数组可以储存成二进制格式，单个的数组保存为 `.npy` 格式，多个数组保存为多个`.npy`文件组成的 `.npz` 格式，每个 `.npy` 文件包含一个数组。

# 与文本格式不同，二进制格式保存了数组的 `shape, dtype` 信息，以便完全重构出保存的数组。

# 保存的方法：

# - `save(file, arr)` 保存单个数组，`.npy` 格式
# - `savez(file, *args, **kwds)` 保存多个数组，无压缩的 `.npz` 格式
# - `savez_compressed(file, *args, **kwds)` 保存多个数组，有压缩的 `.npz` 格式

# 读取的方法：

# - `load(file, mmap_mode=None)` 对于 `.npy`，返回保存的数组，对于 `.npz`，返回一个名称-数组对组成的字典。

In [69]:
# 2.1.单个数组的读写
a = np.array([[1.0,2.0], [3.0,4.0]])

fname = 'afile.npy'
np.save(fname, a)

In [70]:
aa = np.load(fname)
aa

array([[1., 2.],
       [3., 4.]])

In [71]:
# 2.2.保存多个数组
a = np.array([[1.0,2.0], 
              [3.0,4.0]])
b = np.arange(1000)
np.savez('data.npz', a=a, b=b)

In [72]:
# 查看里面包含的文件
!unzip -l data.npz

'unzip' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [77]:
# 载入data
data = np.load('data.npz')
data['a']

array([[1., 2.],
       [3., 4.]])