In [3]:
import pandas as pd
import numpy as np

# pandans的数据结构

## series

1. 通过list构建Series

In [2]:
# 1.使用列表构建
ser_obj = pd.Series(range(11))
print(ser_obj)
ser2 = pd.Series(range(11,16))
print(ser2.head(3))
print(type(ser2))

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
0    11
1    12
2    13
dtype: int64
<class 'pandas.core.series.Series'>


In [19]:
# 2.使用标量构建
pd.Series(5., index=['a', 'b', 'c', 'd', 'e'])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

2. 获取数据和索引

In [3]:
# 获取数据，返回一个列表
print(ser_obj.values) 

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
# 获取索引
print(ser_obj.index)

RangeIndex(start=0, stop=11, step=1)


3. 通过索引获取数据

In [5]:
print(ser_obj[5])
print(ser_obj[0])

5
0


4. 索引与数据的对应关系不被运算结果影响

In [9]:
display(ser_obj*3)
display(ser_obj>7)

0      0
1      3
2      6
3      9
4     12
5     15
6     18
7     21
8     24
9     27
10    30
dtype: int64

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
dtype: bool

5. 通过dict构建Series

In [10]:
year_data = {2001:15.2,2002:74.5,2003:45.2}
ser3 = pd.Series(year_data)
print(ser3)

2001    15.2
2002    74.5
2003    45.2
dtype: float64


name属性

In [11]:
ser3.name="temp"
ser3.index.name="year"
print(ser3.head())

year
2001    15.2
2002    74.5
2003    45.2
Name: temp, dtype: float64


## DataFrame

1. 通过ndarray构建DataFrame

In [13]:
arr = np.random.randn(5,4)
print(arr)
dat = pd.DataFrame(arr)
display(dat.head())
display(dat)

[[-0.6651951   0.99031597  0.01943429  0.62287185]
 [-0.6669378   0.53082008  0.76816148 -0.16160982]
 [-0.4103636  -0.49280522  0.33365319 -1.46168922]
 [-0.18677361  1.69450001 -0.75899808  2.37291368]
 [-0.97649604 -0.59215663  1.46405265  1.98699917]]


0         1         2         3
0 -0.665195  0.990316  0.019434  0.622872
1 -0.666938  0.530820  0.768161 -0.161610
2 -0.410364 -0.492805  0.333653 -1.461689
3 -0.186774  1.694500 -0.758998  2.372914
4 -0.976496 -0.592157  1.464053  1.986999

0         1         2         3
0 -0.665195  0.990316  0.019434  0.622872
1 -0.666938  0.530820  0.768161 -0.161610
2 -0.410364 -0.492805  0.333653 -1.461689
3 -0.186774  1.694500 -0.758998  2.372914
4 -0.976496 -0.592157  1.464053  1.986999

In [16]:
# 根据已有数据创建data
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  2.023348 -0.103618  1.252361  0.135549
2013-01-02  1.133681  1.431383  1.601231  0.750479
2013-01-03 -0.569104  1.322874 -1.733148 -1.160474
2013-01-04 -0.782079 -0.275948  0.802515  1.597505
2013-01-05  1.549878 -0.074659 -1.554708 -0.705787
2013-01-06  0.396418  1.699807 -0.469814  0.486216

2. 通过dict构建DataFrame

In [4]:
dict_data = {'A': 1, 
             'B': pd.Timestamp('20170426'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'ITCast' }
dat1 = pd.DataFrame(dict_data)
display(dat1)

A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast

3. 通过列索引获取列数据（Series类型）

In [5]:
display(dat1["B"])
display(dat1.B)  #.索引

0   2017-04-26
1   2017-04-26
2   2017-04-26
3   2017-04-26
Name: B, dtype: datetime64[ns]

0   2017-04-26
1   2017-04-26
2   2017-04-26
3   2017-04-26
Name: B, dtype: datetime64[ns]

4. 增加列数据

In [8]:
dat1["G"]=dat1["D"] + 5
display(dat1.head())

A          B    C  D       E       F  G
0  1 2017-04-26  1.0  3  Python  ITCast  8
1  1 2017-04-26  1.0  3    Java  ITCast  8
2  1 2017-04-26  1.0  3     C++  ITCast  8
3  1 2017-04-26  1.0  3       C  ITCast  8

5. 删除列

In [9]:
del(dat1['G'])
display(dat1)

A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast

6.查看数据

In [11]:
display(dat1.tail(3))

A          B    C  D     E       F
1  1 2017-04-26  1.0  3  Java  ITCast
2  1 2017-04-26  1.0  3   C++  ITCast
3  1 2017-04-26  1.0  3     C  ITCast

# pandas的索引操作

## 索引对象Index

1. Series和DataFrame中的索引都是Index对象

In [12]:
ser_obj = pd.Series(range(11))
ser2 = pd.Series(range(11,16))
dict_data = {'A': 1, 
             'B': pd.Timestamp('20170426'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'ITCast' }
dat1 = pd.DataFrame(dict_data)

In [13]:
display(ser2.index)
display(dat1.index)
display(dat1.columns)

RangeIndex(start=0, stop=5, step=1)

Int64Index([0, 1, 2, 3], dtype='int64')

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

2. 索引对象不可变，保证了数据的安全

In [14]:
# 不可以更改索引对象，否则报错
dat1.index[1] = 12 

TypeError: Index does not support mutable operations

In [ ]:
# 常见的Index种类
# * Index，索引
# * Int64Index，整数索引
# * MultiIndex，层级索引
# * DatetimeIndex，时间戳类型

## Series索引

1. index 指定行索引名

In [15]:
ser4 = pd.Series(range(5),index=['a','b','c','d','e'])
display(ser4)

a    0
b    1
c    2
d    3
e    4
dtype: int64

2. 行索引

In [16]:
display(ser4['b'])
display(ser4[4])

1

4

3. 切片索引

In [17]:
display(ser4[2:4])
display(ser4['b':'e'])

c    2
d    3
dtype: int64

b    1
c    2
d    3
e    4
dtype: int64

4. 不连续索引

In [18]:
display(ser4[[0,4,3]])
display(ser4[['a','c']])

a    0
e    4
d    3
dtype: int64

a    0
c    2
dtype: int64

5. 布尔索引

In [19]:
ser_bool = ser4 > 3
display(ser_bool)
display(ser4[ser_bool])

a    False
b    False
c    False
d    False
e     True
dtype: bool

e    4
dtype: int64

## DataFrame索引

1. columns 指定列索引名

In [20]:
dat2 = pd.DataFrame(np.random.randn(5,4),columns=['a','b','c','d'])
display(dat2)

a         b         c         d
0 -0.007055  1.827512  2.088607  0.418849
1 -0.470651 -1.287760 -0.012530  0.725030
2  0.445634  1.393086 -1.435379  0.812443
3 -0.905061 -0.344987  0.099889 -0.148613
4 -1.541823 -0.678374  0.565421 -1.280626

2. 列索引

In [21]:
display(dat2['b'])

0    1.827512
1   -1.287760
2    1.393086
3   -0.344987
4   -0.678374
Name: b, dtype: float64

3. 不连续索引

In [22]:
display(dat2[['a','c']]) # 返回元组类型

a         c
0 -0.007055  2.088607
1 -0.470651 -0.012530
2  0.445634 -1.435379
3 -0.905061  0.099889
4 -1.541823  0.565421

4.列索引

In [23]:
# 使用 ：进行索引
display(dat2[1:2])

a        b        c        d
1 -0.470651 -1.28776 -0.01253  0.72503

## 高级索引：标签、位置和混合

1. loc 标签索引

In [24]:
display(ser4['b':'d'])
display(ser4.loc['b':'d'])

b    1
c    2
d    3
dtype: int64

b    1
c    2
d    3
dtype: int64

In [25]:
display(dat2['a'])
display(dat2.loc[0:2,'a'])#基于索引内容

0   -0.007055
1   -0.470651
2    0.445634
3   -0.905061
4   -1.541823
Name: a, dtype: float64

0   -0.007055
1   -0.470651
2    0.445634
Name: a, dtype: float64

2. iloc 位置索引(行和列)

In [26]:
display(ser4[1:3])
display(ser4.iloc[1:3])

b    1
c    2
dtype: int64

b    1
c    2
dtype: int64

In [27]:
display(dat2.iloc[0:2,0]) # 基于索引编号

0   -0.007055
1   -0.470651
Name: a, dtype: float64

# Pandas的运算

## Series的对齐运算

1. Series 按行、索引对齐

In [2]:
s1 = pd.Series(range(10,20), index = range(10))
s2 = pd.Series(range(20,25), index = range(5))
display(s1, s2)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

0    20
1    21
2    22
3    23
4    24
dtype: int64

2. Series的对齐运算

In [3]:
# 计算公共部分，非公共部分为空
display(s1 + s2)

0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

## DataFrame的对齐运算

1. DataFrame按行、列索引对齐

In [4]:
dat3=pd.DataFrame(np.ones((2,2)),columns=['a','b'])
dat4=pd.DataFrame(np.ones((3,3)),columns=['a','b','c'])
display(dat3, dat4)

a    b
0  1.0  1.0
1  1.0  1.0

a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

2. DataFrame的对齐运算

In [5]:
# 计算公共部分，非公共部分为空
display(dat3 + dat4)

a    b   c
0  2.0  2.0 NaN
1  2.0  2.0 NaN
2  NaN  NaN NaN

## 填充未对齐的数据进行运算

1. fill_value

In [6]:
display(s1.add(s2, fill_value=1))
display(dat3.sub(dat4, fill_value=3.))

0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    16.0
6    17.0
7    18.0
8    19.0
9    20.0
dtype: float64

a    b    c
0  0.0  0.0  2.0
1  0.0  0.0  2.0
2  2.0  2.0  2.0

## 算术运算

In [8]:
data = pd.read_csv("./data/stock_day.csv")
data = data.drop(["ma5","ma10","ma20","v_ma5","v_ma10","v_ma20"], axis=1)

In [9]:
# 1.加法计算
data["close"].add(10).head()

2018-02-27    34.16
2018-02-26    33.53
2018-02-23    32.82
2018-02-22    32.28
2018-02-14    31.92
Name: close, dtype: float64

## 逻辑计算

In [10]:
# 1.逻辑运算符号
data[data["open"] > 23].head()

open   high  close    low    volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53  95578.03          0.63      2.68   
2018-02-01  23.71  23.86  22.42  22.22  66414.64         -1.30     -5.48   
2018-01-31  23.85  23.98  23.72  23.31  49155.02         -0.11     -0.46   
2018-01-30  23.71  24.08  23.83  23.70  32420.43          0.05      0.21   
2018-01-29  24.40  24.63  23.77  23.72  65469.81         -0.73     -2.98   

            turnover  
2018-02-27      2.39  
2018-02-01      1.66  
2018-01-31      1.23  
2018-01-30      0.81  
2018-01-29      1.64

In [11]:
data[(data["open"] > 23) & (data["open"] < 24)].head()

open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68   
2018-02-01  23.71  23.86  22.42  22.22   66414.64         -1.30     -5.48   
2018-01-31  23.85  23.98  23.72  23.31   49155.02         -0.11     -0.46   
2018-01-30  23.71  24.08  23.83  23.70   32420.43          0.05      0.21   
2018-01-16  23.40  24.60  24.40  23.30  101295.42          0.96      4.10   

            turnover  
2018-02-27      2.39  
2018-02-01      1.66  
2018-01-31      1.23  
2018-01-30      0.81  
2018-01-16      2.54

In [12]:
# 2.逻辑运算函数
data.query("open<24 & open>23").head()

open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68   
2018-02-01  23.71  23.86  22.42  22.22   66414.64         -1.30     -5.48   
2018-01-31  23.85  23.98  23.72  23.31   49155.02         -0.11     -0.46   
2018-01-30  23.71  24.08  23.83  23.70   32420.43          0.05      0.21   
2018-01-16  23.40  24.60  24.40  23.30  101295.42          0.96      4.10   

            turnover  
2018-02-27      2.39  
2018-02-01      1.66  
2018-01-31      1.23  
2018-01-30      0.81  
2018-01-16      2.54

In [13]:
data[data["open"].isin([23.53, 23.85])]

open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68   
2018-01-31  23.85  23.98  23.72  23.31   49155.02         -0.11     -0.46   
2017-07-26  23.53  23.92  23.40  22.85  110276.48         -0.30     -1.27   
2015-12-18  23.53  24.66  23.99  23.43  109230.05          0.65      2.79   
2015-11-26  23.85  24.08  23.53  23.50   51446.29         -0.31     -1.30   

            turnover  
2018-02-27      2.39  
2018-01-31      1.23  
2017-07-26      2.76  
2015-12-18      3.74  
2015-11-26      1.76

# Pandas的函数应用

## apply 和 applymap

1. 可直接使用NumPy的函数

In [28]:
dat5 = pd.DataFrame(np.random.randn(5,4)-1)
display(dat5)
display(dat5.abs())

0         1         2         3
0 -1.723869 -1.344591 -1.078933  0.174992
1 -1.566607  0.352849 -0.046500 -2.366547
2 -1.045265 -2.604946 -0.950434  1.333952
3 -0.832610  0.780150 -0.020224 -2.029927
4 -1.970221  0.712482 -0.921493 -0.603046

0         1         2         3
0  1.723869  1.344591  1.078933  0.174992
1  1.566607  0.352849  0.046500  2.366547
2  1.045265  2.604946  0.950434  1.333952
3  0.832610  0.780150  0.020224  2.029927
4  1.970221  0.712482  0.921493  0.603046

2. 通过apply将函数应用到列或行上

In [29]:
# 注意指定轴的方向，默认axis=0，方向是列
display(dat5.apply(lambda x:x.max()))

0   -0.832610
1    0.780150
2   -0.020224
3    1.333952
dtype: float64

In [30]:
# 注意指定轴的方向，默认axis=1，方向是行
display(dat5.apply(lambda x:x.max(),axis=1))

0    0.174992
1    0.352849
2    1.333952
3    0.780150
4    0.712482
dtype: float64

3. 通过applymap将函数应用到每个数据上

In [31]:
f1 = lambda x: "%.2f" %x
display(dat5.applymap(f1))

0      1      2      3
0  -1.72  -1.34  -1.08   0.17
1  -1.57   0.35  -0.05  -2.37
2  -1.05  -2.60  -0.95   1.33
3  -0.83   0.78  -0.02  -2.03
4  -1.97   0.71  -0.92  -0.60

## 排序

1. 索引排序

In [32]:
s4 = pd.Series(range(10,15),index=np.random.randint(5,size=5))
display(s4)
s4.sort_index()

0    10
2    11
3    12
4    13
4    14
dtype: int64

0    10
2    11
3    12
4    13
4    14
dtype: int64

In [33]:
# 对DataFrame操作时注意轴方向
dat6=pd.DataFrame(np.random.randn(3,5),
                  index=np.random.randint(3,size=3),
                 columns=np.random.randint(5,size=5))
display(dat6)
dat6_isort = dat6.sort_index(axis=1,ascending=False)
display(dat6_isort)
dat6_jsort = dat6.sort_index(axis=1,ascending=True)
display(dat6_jsort)

4         3         0         2         3
1  0.120062 -1.384446  0.420254 -1.377769 -1.313627
0 -3.132509  1.501817 -0.198134  1.662789  0.982152
0  0.994159 -1.117589 -0.236353  1.514271 -0.078514

4         3         3         2         0
1  0.120062 -1.384446 -1.313627 -1.377769  0.420254
0 -3.132509  1.501817  0.982152  1.662789 -0.198134
0  0.994159 -1.117589 -0.078514  1.514271 -0.236353

0         2         3         3         4
1  0.420254 -1.377769 -1.384446 -1.313627  0.120062
0 -0.198134  1.662789  1.501817  0.982152 -3.132509
0 -0.236353  1.514271 -1.117589 -0.078514  0.994159

2. 按值排序

In [34]:
dat6_vsort = dat6.sort_values(by = 4, ascending = False)
display(dat6_vsort)

4         3         0         2         3
0  0.994159 -1.117589 -0.236353  1.514271 -0.078514
1  0.120062 -1.384446  0.420254 -1.377769 -1.313627
0 -3.132509  1.501817 -0.198134  1.662789  0.982152

3.dataframe转换成list

In [35]:
li=pd.Series([4,31,5,51,3,7],index=['a','b','c','d','e','f'])
li=li.tolist()
li

[4, 31, 5, 51, 3, 7]

## 处理缺失数据

In [55]:
dat7 = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(dat7)

          0         1         2
0  0.223347 -1.318415 -1.258266
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


1. 判断是否存在缺失值：isnull()

In [56]:
print(dat7.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


2. 丢弃缺失数据：dropna()

In [57]:
#根据axis轴方向，丢弃包含NaN的行或列
print(dat7.dropna(axis=1))
print(dat7.dropna(axis=0))

          1
0 -1.318415
1  2.000000
2  4.000000
3  2.000000
          0         1         2
0  0.223347 -1.318415 -1.258266
3  1.000000  2.000000  3.000000


3. 填充缺失数据：fillna()

In [58]:
print(dat7.fillna(101.))

            0         1           2
0    0.223347 -1.318415   -1.258266
1    1.000000  2.000000  101.000000
2  101.000000  4.000000  101.000000
3    1.000000  2.000000    3.000000


# 层级索引

In [36]:
ser5=pd.Series(np.random.randn(12),index=[
                ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]])
display(ser5)

a  0   -1.212896
   1   -0.623791
   2   -0.338658
b  0    0.743303
   1   -0.204207
   2   -0.484520
c  0    1.188887
   1   -0.158689
   2    0.345411
d  0    0.101808
   1   -0.003620
   2   -1.405254
dtype: float64

## MultiIndex索引对象

In [37]:
display(type(ser5.index))
display(ser5.index)

pandas.core.indexes.multi.MultiIndex

MultiIndex([('a', 0),
            ('a', 1),
            ('a', 2),
            ('b', 0),
            ('b', 1),
            ('b', 2),
            ('c', 0),
            ('c', 1),
            ('c', 2),
            ('d', 0),
            ('d', 1),
            ('d', 2)],
           )

## 选取子集

1. 外层选取：

In [38]:
display(ser5['b'])

0    0.743303
1   -0.204207
2   -0.484520
dtype: float64

2. 内层选取：

In [39]:
display(ser5[:,2])

a   -0.338658
b   -0.484520
c    0.345411
d   -1.405254
dtype: float64

## 交换分层顺序

In [40]:
#.swaplevel( )交换内层与外层索引。
display(ser5.swaplevel())

0  a   -1.212896
1  a   -0.623791
2  a   -0.338658
0  b    0.743303
1  b   -0.204207
2  b   -0.484520
0  c    1.188887
1  c   -0.158689
2  c    0.345411
0  d    0.101808
1  d   -0.003620
2  d   -1.405254
dtype: float64

## 交换并排序分层

In [41]:
# sort_index()先对外层索引进行排序，再对内层索引进行排序，默认是升序
display(ser5.swaplevel().sort_index())

0  a   -1.212896
   b    0.743303
   c    1.188887
   d    0.101808
1  a   -0.623791
   b   -0.204207
   c   -0.158689
   d   -0.003620
2  a   -0.338658
   b   -0.484520
   c    0.345411
   d   -1.405254
dtype: float64

# Pandas统计计算和描述

In [14]:
# axis=0 按列统计，axis=1按行统计
dat8 = pd.DataFrame(np.random.randn(5,4),columns=['a','b','c','d'])
display(dat8)

a         b         c         d
0  0.338188 -0.089179 -1.211417  0.435774
1  0.880119 -0.515188  1.395227 -0.792657
2 -0.633184 -0.335533 -0.711776 -0.288377
3  0.309186  0.283303  0.736081  0.012829
4 -0.403026 -1.367406  0.131844 -0.328012

## 常用的统计计算

In [15]:
display(dat8.sum())

a    0.491283
b   -2.024003
c    0.339960
d   -0.960443
dtype: float64

In [16]:
display(dat8.max())

a    0.880119
b    0.283303
c    1.395227
d    0.435774
dtype: float64

In [17]:
#skipna 排除缺失值， 默认为True
display(dat8.min(axis=1, skipna=False))

0   -1.211417
1   -0.792657
2   -0.711776
3    0.012829
4   -1.367406
dtype: float64

## 常用的统计描述

In [18]:
# 1.describe 产生多个统计数据
display(dat8.describe())

a         b         c         d
count  5.000000  5.000000  5.000000  5.000000
mean   0.098257 -0.404801  0.067992 -0.192089
std    0.612302  0.615771  1.055568  0.454046
min   -0.633184 -1.367406 -1.211417 -0.792657
25%   -0.403026 -0.515188 -0.711776 -0.328012
50%    0.309186 -0.335533  0.131844 -0.288377
75%    0.338188 -0.089179  0.736081  0.012829
max    0.880119  0.283303  1.395227  0.435774

## 缺失值处理

In [19]:
# 1.导入data
movie = pd.read_csv("./data/IMDB-Movie-Data.csv")
display(movie.head())

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [20]:
# 2.判断缺失值
# 2.1里面如果有一个缺失值,就返回True
np.any(pd.isnull(movie))  

True

In [21]:
# 2.2里面如果有一个缺失值,就返回False
np.all(pd.notnull(movie))  

False

In [23]:
# 3.去除缺失值
data = movie.dropna()
np.any(pd.isnull(data))

False

# Pandas分组与聚合

## 分组 (groupby)

In [ ]:
# * 对数据集进行分组，然后对每组进行统计分析

# * SQL能够对数据进行过滤，分组聚合

# * pandas能利用groupby进行更加复杂的分组运算

# * 分组运算过程：split->apply->combine

# 1. 拆分：进行分组的根据

# 2. 应用：每个分组运行的计算规则

# 3. 合并：把每个分组的计算结果合并起来

In [2]:
dict_obj={  "key1":['a', 'b', 'a', 'b', 
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randn(8),
            'data2': np.random.randn(8)}
data=pd.DataFrame(dict_obj)
display(data)

key1   key2     data1     data2
0    a    one  0.087080 -0.181023
1    b    one -1.460627 -0.371783
2    a    two  0.029736 -1.777923
3    b  three  2.837833 -0.621131
4    a    two  1.512322 -1.200086
5    b    two  1.666812 -1.162930
6    a    one -0.307175 -0.781217
7    a  three  0.457428 -1.022914

### GroupBy对象：DataFrameGroupBy，SeriesGroupBy

#### 1. 分组操作

In [ ]:
# groupby()进行分组，GroupBy对象没有进行实际运算，只是包含分组的中间数据
# 按列名分组：obj.groupby(‘label’)

In [3]:
display(type(data.groupby('key1')))

pandas.core.groupby.generic.DataFrameGroupBy

In [4]:
# dataframe的 data1 列根据 key1 进行分组
display(data['data1'].groupby(data['key1']))

#### 2. 分组运算

In [ ]:
# 对GroupBy对象进行分组运算/多重分组运算，如mean()
# 非数值数据不进行分组运算

In [5]:
# 分组运算
grouped1 = data.groupby('key1')
display(grouped1.mean())
grouped2 = data['data1'].groupby(data['key1'])
display(grouped2.mean())

data1     data2
key1                    
a     0.355878 -0.992632
b     1.014673 -0.718615

key1
a    0.355878
b    1.014673
Name: data1, dtype: float64

In [6]:
# size() 返回每个分组的元素个数
print(grouped1.size())
print(grouped2.size())

key1
a    5
b    3
dtype: int64
key1
a    5
b    3
Name: data1, dtype: int64


#### 3. 按自定义的key分组

In [ ]:
# obj.groupby(self_def_key)
# 自定义的key可为列表或多层列表
# obj.groupby([‘label1’, ‘label2’])->多层dataframe

In [7]:
# 按自定义key分组，列表
self_key = [0,1,2,3,4,5,6,7]
display(data.groupby(self_key).size())

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
dtype: int64

In [8]:
# 按自定义key分组，多层列表
display(data.groupby([data['key1'], data['key2']]).size())

key1  key2 
a     one      2
      three    1
      two      2
b     one      1
      three    1
      two      1
dtype: int64

In [9]:
# 按多个列多层分组
grouped3 = data.groupby(['key1','key2'])
print(grouped3.size())

key1  key2 
a     one      2
      three    1
      two      2
b     one      1
      three    1
      two      1
dtype: int64


In [10]:
# 多层分组按key的顺序进行
grouped4 = data.groupby(['key2','key1'])
print(grouped4.mean())

               data1     data2
key2  key1                    
one   a    -0.110048 -0.481120
      b    -1.460627 -0.371783
three a     0.457428 -1.022914
      b     2.837833 -0.621131
two   a     0.771029 -1.489004
      b     1.666812 -1.162930


In [11]:
# unstack可以将多层索引的结果转换成单层的dataframe
display(grouped3.mean().unstack())

data1                         data2                    
key2       one     three       two       one     three       two
key1                                                            
a    -0.110048  0.457428  0.771029 -0.481120 -1.022914 -1.489004
b    -1.460627  2.837833  1.666812 -0.371783 -0.621131 -1.162930

### 二、GroupBy对象支持迭代操作

In [ ]:
# 每次迭代返回一个元组 (group_name, group_data)
# 可用于分组数据的具体运算

#### 1. 单层分组

In [12]:
# 单层分组，根据key1
for g_name,g_data in grouped1:
    display(g_name)
    display(g_data)

'a'

key1   key2     data1     data2
0    a    one  0.087080 -0.181023
2    a    two  0.029736 -1.777923
4    a    two  1.512322 -1.200086
6    a    one -0.307175 -0.781217
7    a  three  0.457428 -1.022914

'b'

key1   key2     data1     data2
1    b    one -1.460627 -0.371783
3    b  three  2.837833 -0.621131
5    b    two  1.666812 -1.162930

### 2. 多层分组

In [13]:
# 多层分组，根据key1 和 key2
for g1_name,g1_data in grouped3:
    display(g1_name)
    display(g1_data)

('a', 'one')

key1 key2     data1     data2
0    a  one  0.087080 -0.181023
6    a  one -0.307175 -0.781217

('a', 'three')

key1   key2     data1     data2
7    a  three  0.457428 -1.022914

('a', 'two')

key1 key2     data1     data2
2    a  two  0.029736 -1.777923
4    a  two  1.512322 -1.200086

('b', 'one')

key1 key2     data1     data2
1    b  one -1.460627 -0.371783

('b', 'three')

key1   key2     data1     data2
3    b  three  2.837833 -0.621131

('b', 'two')

key1 key2     data1    data2
5    b  two  1.666812 -1.16293

### 三、GroupBy对象可以转换成列表或字典

In [14]:
# GroupBy对象转换list
display(list(grouped1))

[('a',
    key1   key2     data1     data2
  0    a    one  0.087080 -0.181023
  2    a    two  0.029736 -1.777923
  4    a    two  1.512322 -1.200086
  6    a    one -0.307175 -0.781217
  7    a  three  0.457428 -1.022914),
 ('b',
    key1   key2     data1     data2
  1    b    one -1.460627 -0.371783
  3    b  three  2.837833 -0.621131
  5    b    two  1.666812 -1.162930)]

In [15]:
# GroupBy对象转换dict
display(dict(list(grouped1)))

{'a':   key1   key2     data1     data2
 0    a    one  0.087080 -0.181023
 2    a    two  0.029736 -1.777923
 4    a    two  1.512322 -1.200086
 6    a    one -0.307175 -0.781217
 7    a  three  0.457428 -1.022914,
 'b':   key1   key2     data1     data2
 1    b    one -1.460627 -0.371783
 3    b  three  2.837833 -0.621131
 5    b    two  1.666812 -1.162930}

#### 1. 按列分组、按数据类型分组

In [16]:
# 按列分组
display(data.dtypes)

key1      object
key2      object
data1    float64
data2    float64
dtype: object

In [17]:
# 按数据类型分组
display(data.groupby(data.dtypes,axis=1).size())
display(data.groupby(data.dtypes,axis=1).sum())

float64    2
object     2
dtype: int64

float64  object
0 -0.093943    aone
1 -1.832409    bone
2 -1.748187    atwo
3  2.216701  bthree
4  0.312237    atwo
5  0.503882    btwo
6 -1.088392    aone
7 -0.565486  athree

#### 2. 其他分组方法

In [19]:
da1 = pd.DataFrame(np.random.randint(1, 10, (5,5)),
                       columns=['a', 'b', 'c', 'd', 'e'],
                       index=['A', 'B', 'C', 'D', 'E'])
da1.iloc[1,1:4]=np.NaN
display(da1)

a    b    c    d  e
A  3  8.0  3.0  8.0  7
B  6  NaN  NaN  NaN  9
C  6  4.0  2.0  7.0  6
D  3  2.0  2.0  3.0  4
E  6  4.0  6.0  9.0  1

#### 3. 通过字典分组

In [21]:
ma_dict = {'a':'Python', 'b':'Python', 'c':'Java', 'd':'C', 'e':'Java'}

In [22]:
display(da1.groupby(ma_dict, axis=1).size())

C         1
Java      2
Python    2
dtype: int64

In [23]:
display(da1.groupby(ma_dict,axis=1).count())

C  Java  Python
A  1     2       2
B  0     1       1
C  1     2       2
D  1     2       2
E  1     2       2

In [24]:
display(da1.groupby(ma_dict,axis=1).count())

C  Java  Python
A  1     2       2
B  0     1       1
C  1     2       2
D  1     2       2
E  1     2       2

In [25]:
display(da1.groupby(ma_dict,axis=1).sum())

C  Java  Python
A  8.0  10.0    11.0
B  0.0   9.0     6.0
C  7.0   8.0    10.0
D  3.0   6.0     5.0
E  9.0   7.0    10.0

#### 4. 通过函数分组，函数传入的参数为行索引或列索引

In [26]:
da2 = pd.DataFrame(np.random.randint(1, 10, (5,5)),
                       columns=['a', 'b', 'c', 'd', 'e'],
                       index=['AA', 'BBB', 'CC', 'D', 'EE'])
display(da2)

a  b  c  d  e
AA   9  7  2  4  2
BBB  4  2  8  5  1
CC   7  3  4  2  6
D    9  8  9  3  3
EE   3  6  3  5  8

In [27]:
def group_key(idx):
    return len(idx)
display(da2.groupby(group_key).size())

1    1
2    3
3    1
dtype: int64

#### 5. 通过索引级别分组

In [28]:
columns = pd.MultiIndex.from_arrays([['Python', 'Java', 'Python', 'Java', 'Python'],
                                     ['A', 'A', 'B', 'C', 'B']], names=['language', 'index'])

In [29]:
da1 = pd.DataFrame(np.random.randint(1,10,(5,5)),columns=columns)
display(da1)

language Python Java Python Java Python
index         A    A      B    C      B
0             7    1      2    5      8
1             8    7      6    5      7
2             5    3      5    5      9
3             1    7      1    5      7
4             4    5      2    3      3

## 聚合 (aggregation)

In [ ]:
# 数组产生标量的过程，如mean()、count()等
# 常用于对分组后的数据进行计算

In [30]:
dic1 = {'key1' : ['a', 'b', 'a', 'b', 
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1,10, 8),
            'data2': np.random.randint(1,10, 8)}

In [32]:
dic1 = pd.DataFrame(dic1)
display(dic1)

key1   key2  data1  data2
0    a    one      5      2
1    b    one      9      2
2    a    two      6      4
3    b  three      5      8
4    a    two      1      7
5    b    two      2      7
6    a    one      3      2
7    a  three      9      6

#### 1. 内置的聚合函数

In [ ]:
# sum(), mean(), max(), min(), count(), size(), describe()

In [33]:
display(dic1.groupby('key1').count())

key2  data1  data2
key1                    
a        5      5      5
b        3      3      3

In [34]:
# 统计key1中索引的个数
display(dic1.groupby('key1').size())  

key1
a    5
b    3
dtype: int64

In [35]:
display(dic1.groupby('key2').size())

key2
one      3
three    2
two      3
dtype: int64

In [36]:
# 统计关键词的个数
display(dic1.groupby('key2').count())

key1  data1  data2
key2                     
one       3      3      3
three     2      2      2
two       3      3      3

In [37]:
display(dic1.groupby('key1').describe())

data1                                              data2            \
     count      mean       std  min  25%  50%  75%  max count      mean   
key1                                                                      
a      5.0  4.800000  3.033150  1.0  3.0  5.0  6.0  9.0   5.0  4.200000   
b      3.0  5.333333  3.511885  2.0  3.5  5.0  7.0  9.0   3.0  5.666667   

                                         
           std  min  25%  50%  75%  max  
key1                                     
a     2.280351  2.0  2.0  4.0  6.0  7.0  
b     3.214550  2.0  4.5  7.0  7.5  8.0

#### 2. 可自定义函数，传入agg方法中

In [ ]:
# grouped.agg(func)
# func的参数为groupby索引对应的记录

In [38]:
def pak(df):
    return df.max()-df.min()

In [39]:
display(dic1.groupby('key1').agg(pak))

C:\Users\17677\AppData\Local\Temp\ipykernel_13228\2332055471.py:1: FutureWarning: ['key2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  display(dic1.groupby('key1').agg(pak))


data1  data2
key1              
a         8      5
b         7      6

#### 3. 应用多个聚合函数

In [ ]:
# 同时应用多个函数进行聚合操作，使用函数列表

In [40]:
 # 默认列名为函数名
display(dic1.groupby('key1').agg(['mean','std','count',pak]))

C:\Users\17677\AppData\Local\Temp\ipykernel_13228\3904844620.py:2: FutureWarning: ['key2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  display(dic1.groupby('key1').agg(['mean','std','count',pak]))


data1                         data2                    
          mean       std count pak      mean       std count pak
key1                                                            
a     4.800000  3.033150     5   8  4.200000  2.280351     5   5
b     5.333333  3.511885     3   7  5.666667  3.214550     3   6

In [41]:
# 通过元组提供新的列名
display(dic1.groupby('key1').agg(['mean', 'std', 'count', ('range', pak)]))

C:\Users\17677\AppData\Local\Temp\ipykernel_13228\3676885552.py:2: FutureWarning: ['key2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  display(dic1.groupby('key1').agg(['mean', 'std', 'count', ('range', pak)]))


data1                           data2                      
          mean       std count range      mean       std count range
key1                                                                
a     4.800000  3.033150     5     8  4.200000  2.280351     5     5
b     5.333333  3.511885     3     7  5.666667  3.214550     3     6

#### 4. 对不同的列分别作用不同的聚合函数，使用dict

In [42]:
dict = {'data1':'mean','data2':'sum'}
display(dic1.groupby('key2').agg(dict))

data1  data2
key2                  
one    5.666667      6
three  7.000000     14
two    3.000000     18

In [43]:
dict1 = {'data1':['mean','max'],
                'data2':'sum'}
display(dic1.groupby('key1').agg(dict1))

data1     data2
          mean max   sum
key1                    
a     4.800000   9    21
b     5.333333   9    17

## 数据的分组运算

In [44]:
dic2 = {'key1' : ['a', 'b', 'a', 'b', 
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1, 10, 8),
            'data2': np.random.randint(1, 10, 8)}

In [46]:
dic2 = pd.DataFrame(dic2)
display(dic2)

key1   key2  data1  data2
0    a    one      3      4
1    b    one      9      3
2    a    two      4      8
3    b  three      4      4
4    a    two      6      5
5    b    two      4      8
6    a    one      2      7
7    a  three      3      4

In [47]:
# 按key1分组后，计算data1，data2的统计信息并附加到原始表格中，并添加表头前缀
k1_sum = dic2.groupby('key1').sum().add_prefix('sum_')
display(k1_sum)

sum_data1  sum_data2
key1                      
a            18         28
b            17         15

1. merge进行外连接

In [ ]:
# left_on：左边数据表的"外键"
# right_on：右边数据表的"外键"
# left_index：使用左边的DataFrame对象的行索引做为连接健
# right_index：使用右边的DataFrame对象的行索引做为连接健
# 一般情况下，外键和连接健的方向是相反的。

In [48]:
# 左外连接
k1_mer_sum = pd.merge(dic1, k1_sum, left_on='key1', right_index=True)
display(k1_mer_sum)

key1   key2  data1  data2  sum_data1  sum_data2
0    a    one      5      2         18         28
2    a    two      6      4         18         28
4    a    two      1      7         18         28
6    a    one      3      2         18         28
7    a  three      9      6         18         28
1    b    one      9      2         17         15
3    b  three      5      8         17         15
5    b    two      2      7         17         15

2.transform合并

In [51]:
# 第二种方法，使用transform进行聚合运算， 运算结果和原始数据形状保持一致
key1_trans = dic2.groupby("key1").transform(sum).add_prefix("sum_")
# 将key1_trans 的列数据添加到原始数据里
dic2[key1_trans.columns] = key1_trans
display(dic2)

key1   key2  data1  data2           sum_key2 sum_data1 sum_data2  \
0    a    one      3      4  onetwotwoonethree        18        28   
1    b    one      9      3        onethreetwo        17        15   
2    a    two      4      8  onetwotwoonethree        18        28   
3    b  three      4      4        onethreetwo        17        15   
4    a    two      6      5  onetwotwoonethree        18        28   
5    b    two      4      8        onethreetwo        17        15   
6    a    one      2      7  onetwotwoonethree        18        28   
7    a  three      3      4  onetwotwoonethree        18        28   

                                        sum_sum_key2 sum_sum_data1  \
0  onetwotwoonethreeonetwotwoonethreeonetwotwoone...            90   
1                  onethreetwoonethreetwoonethreetwo            51   
2  onetwotwoonethreeonetwotwoonethreeonetwotwoone...            90   
3                  onethreetwoonethreetwoonethreetwo            51   
4  onetwotwoonethreeonetwotwoonethreeonetwotwoone...            90   
5                  onethreetwoonethreetwoonethreetwo            51   
6  onetwotwoonethreeonetwotwoonethreeonetwotwoone...            90   
7  onetwotwoonethreeonetwotwoonethreeonetwotwoone...            90   

  sum_sum_data2  
0           140  
1            45  
2           140  
3            45  
4           140  
5            45  
6           140  
7           140

# 数据清洗

## 数据连接(pd.merge)

In [ ]:
# pd.merge
# 根据单个或多个键将不同DataFrame的行连接起来
# 类似数据库的连接操作

In [52]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data2' : np.random.randint(0,10,3)})

In [53]:
display(df1)
display(df2)

key  data1
0   b      7
1   b      4
2   a      7
3   c      2
4   a      3
5   a      0
6   b      2

key  data2
0   a      0
1   b      1
2   d      7

1. 默认将重叠列的列名作为“外键”进行连接

In [54]:
display(pd.merge(df1,df2))

key  data1  data2
0   b      7      1
1   b      4      1
2   b      2      1
3   a      7      0
4   a      3      0
5   a      0      0

2. on显示指定“外键”

In [55]:
display(pd.merge(df1,df2,on='key'))

key  data1  data2
0   b      7      1
1   b      4      1
2   b      2      1
3   a      7      0
4   a      3      0
5   a      0      0

3. left_on，左侧数据的“外键”，right_on，右侧数据的“外键”

In [57]:
# 更改列名
dat1 = df1.rename(columns={'key':'key1'})
dat2 = df2.rename(columns={'key':'key2'})

In [58]:
display(pd.merge(dat1,dat2,left_on='key1',right_on='key2'))

key1  data1 key2  data2
0    b      7    b      1
1    b      4    b      1
2    b      2    b      1
3    a      7    a      0
4    a      3    a      0
5    a      0    a      0

In [ ]:
# 默认是“内连接”(inner)，即结果中的键是交集
# how指定连接方式

4. “外连接”(outer)，结果中的键是并集

In [59]:
display(pd.merge(dat1,dat2,left_on='key1',right_on='key2',how='outer'))

key1  data1 key2  data2
0    b    7.0    b    1.0
1    b    4.0    b    1.0
2    b    2.0    b    1.0
3    a    7.0    a    0.0
4    a    3.0    a    0.0
5    a    0.0    a    0.0
6    c    2.0  NaN    NaN
7  NaN    NaN    d    7.0

5. “左连接”(left)

In [60]:
display(pd.merge(dat1,dat2,left_on='key1',right_on='key2',how='left'))

key1  data1 key2  data2
0    b      7    b    1.0
1    b      4    b    1.0
2    a      7    a    0.0
3    c      2  NaN    NaN
4    a      3    a    0.0
5    a      0    a    0.0
6    b      2    b    1.0

6. “右连接”(right)

In [61]:
display(pd.merge(dat1,dat2,left_on='key1',right_on='key2',how='right'))

key1  data1 key2  data2
0    a    7.0    a      0
1    a    3.0    a      0
2    a    0.0    a      0
3    b    7.0    b      1
4    b    4.0    b      1
5    b    2.0    b      1
6  NaN    NaN    d      7

7. 处理重复列名

In [ ]:
# suffixes，默认为_x, _y

In [62]:
dat3 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
dat4= pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})

In [63]:
display(dat3)
display(dat4)

key  data
0   b     8
1   b     6
2   a     2
3   c     6
4   a     7
5   a     7
6   b     1

key  data
0   a     0
1   b     5
2   d     8

In [65]:
display(pd.merge(dat3,dat4,on='key',suffixes=('_left','_right')))

key  data_left  data_right
0   b          8           5
1   b          6           5
2   b          1           5
3   a          2           0
4   a          7           0
5   a          7           0

8. 按索引连接

In [ ]:
# left_index=True或right_index=True

In [51]:
df3 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df4 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])

In [52]:
print(pd.merge(df3,df4,left_on='key',right_index=True))

  key  data1  data2
0   b      3      8
1   b      3      8
6   b      5      8
2   a      0      3
4   a      7      3
5   a      0      3


## 数据合并(pd.concat)

1. NumPy的concat

In [53]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))
print(arr1)
print(arr2)

[[3 2 3 0]
 [8 3 8 4]
 [4 9 9 0]]
[[8 1 1 7]
 [0 2 6 2]
 [7 4 2 3]]


In [54]:
print(np.concatenate([arr1,arr2]))

[[3 2 3 0]
 [8 3 8 4]
 [4 9 9 0]
 [8 1 1 7]
 [0 2 6 2]
 [7 4 2 3]]


In [55]:
print(np.concatenate([arr1,arr2],axis=1))

[[3 2 3 0 8 1 1 7]
 [8 3 8 4 0 2 6 2]
 [4 9 9 0 7 4 2 3]]


2. pd.concat

In [ ]:
# 注意指定轴方向，默认axis=0

# join指定合并方式，默认为outer

# Series合并时查看行索引有无重复

1) index 没有重复的情况

In [56]:
ser1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

In [57]:
print(ser1)
print(ser2)
print(ser3)

0    9
1    2
2    7
3    0
4    3
dtype: int32
5    9
6    4
7    6
8    5
dtype: int32
9     1
10    4
11    7
dtype: int32


In [113]:
print(pd.concat([ser1,ser2,ser3]))

0     8
1     1
2     8
3     5
4     8
5     2
6     9
7     2
8     9
9     9
10    3
11    6
dtype: int32


In [58]:
print(pd.concat([ser1,ser2,ser3],axis=1))

      0    1    2
0   9.0  NaN  NaN
1   2.0  NaN  NaN
2   7.0  NaN  NaN
3   0.0  NaN  NaN
4   3.0  NaN  NaN
5   NaN  9.0  NaN
6   NaN  4.0  NaN
7   NaN  6.0  NaN
8   NaN  5.0  NaN
9   NaN  NaN  1.0
10  NaN  NaN  4.0
11  NaN  NaN  7.0


2) index 有重复的情况

In [59]:
# index 有重复的情况
ser4 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser5 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser6 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

In [60]:
print(ser4)
print(ser5)
print(ser6)

0    9
1    7
2    7
3    4
4    2
dtype: int32
0    8
1    4
2    1
3    0
dtype: int32
0    9
1    1
2    6
dtype: int32


In [61]:
print(pd.concat([ser4,ser5,ser6]))

0    9
1    7
2    7
3    4
4    2
0    8
1    4
2    1
3    0
0    9
1    1
2    6
dtype: int32


3) DataFrame合并时同时查看行索引和列索引有无重复

In [62]:
df4= pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df5 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])

In [63]:
print(df4)
print(df5)

   A  B
a  5  7
b  9  7
c  2  3
   C  D
a  5  9
b  9  8


In [64]:
print(pd.concat([df4,df5]))

     A    B    C    D
a  5.0  7.0  NaN  NaN
b  9.0  7.0  NaN  NaN
c  2.0  3.0  NaN  NaN
a  NaN  NaN  5.0  9.0
b  NaN  NaN  9.0  8.0


In [65]:
print(pd.concat([df4,df5],axis=1,join='inner'))

   A  B  C  D
a  5  7  5  9
b  9  7  9  8


## 数据重构

In [ ]:
# 1. stack
# 将列索引旋转为行索引，完成层级索引
# DataFrame->Series

In [66]:
da1 = pd.DataFrame(np.random.randint(0,10, (5,2)), columns=['data1', 'data2'])

In [67]:
print(da1)

   data1  data2
0      7      2
1      9      4
2      2      0
3      1      3
4      2      2


In [68]:
stacked=da1.stack()
print(stacked)

0  data1    7
   data2    2
1  data1    9
   data2    4
2  data1    2
   data2    0
3  data1    1
   data2    3
4  data1    2
   data2    2
dtype: int32


2. unstack

In [ ]:
# 将层级索引展开

# Series->DataFrame

# 认操作内层索引，即level=-1

In [69]:
print(stacked.unstack())

   data1  data2
0      7      2
1      9      4
2      2      0
3      1      3
4      2      2


In [70]:
# 通过level指定操作索引的级别
print(stacked.unstack(level=0))

       0  1  2  3  4
data1  7  9  2  1  2
data2  2  4  0  3  2


## 数据转换

一、 处理重复数据

1 duplicated() 返回布尔型Series表示每行是否为重复行

In [71]:
dfx = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})

In [72]:
print(dfx)

  data1  data2
0     a      0
1     a      1
2     a      0
3     a      1
4     b      2
5     b      2
6     b      2
7     b      1


In [73]:
print(dfx.duplicated())

0    False
1    False
2     True
3     True
4    False
5     True
6     True
7    False
dtype: bool


2 drop_duplicates() 过滤重复行

In [74]:
print(dfx.drop_duplicates())

  data1  data2
0     a      0
1     a      1
4     b      2
7     b      1


In [75]:
print(dfx.drop_duplicates('data2'))

  data1  data2
0     a      0
1     a      1
4     b      2


3. 根据map传入的函数对每行或每列进行转换

Series根据map传入的函数对每行或每列进行转换

In [76]:
ser6 = pd.Series(np.random.randint(0,10,10))

In [77]:
print(ser6)

0    4
1    5
2    9
3    7
4    5
5    0
6    9
7    4
8    7
9    7
dtype: int32


In [78]:
print(ser6.map(lambda x:x**2))

0    16
1    25
2    81
3    49
4    25
5     0
6    81
7    16
8    49
9    49
dtype: int64


二、数据替换

replace根据值的内容进行替换

In [79]:
# 单个值替换单个值
print(ser6.replace(1,-10))

0    4
1    5
2    9
3    7
4    5
5    0
6    9
7    4
8    7
9    7
dtype: int32


In [80]:
# 多个值替换一个值
print(ser6.replace([6,8],-11))

0    4
1    5
2    9
3    7
4    5
5    0
6    9
7    4
8    7
9    7
dtype: int32


In [81]:
# 多个值替换多个值
print(ser6.replace([5,9],[1000,2222]))

0       4
1    1000
2    2222
3       7
4    1000
5       0
6    2222
7       4
8       7
9       7
dtype: int32
