In [1]:
#1.
dicts = {}
dicts[(1, 2)] = ({3, (4, 5)})
print(dicts)
#字典的键必须是可哈希的

{(1, 2): {(4, 5), 3}}


In [2]:
import copy
a = [1, 2, 3, 4, ['a', 'b']]
b = a
c = copy.copy(a)
d = copy.deepcopy(a)
a.append(5)
a[4].append('c')
print(a)

[1, 2, 3, 4, ['a', 'b', 'c'], 5]


In [3]:
#2.center()返回指定宽度的字符串
a='abc'
print(a.center(10, '*'))

***abc****


In [4]:
#3.字典去重
c=[1,1,5,5]
b = {}
b = list(c.fromkeys(a))

AttributeError: 'list' object has no attribute 'fromkeys'

In [1]:
import torch

In [2]:
X=torch.Tensor([[-1,0.,2,1],
                 [0,3,0,-3],
                 [0,-1,1,0],
                 [2,4,0,2]])

In [20]:
X_res=torch.inverse(X)
X_res.shape

torch.Size([4, 4])

In [19]:
x=torch.Tensor([[2],[0],[0],[8]])
x.shape

torch.Size([4, 1])

In [21]:
print(torch.dot(x,X_res))

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [1]:
import numpy as np

In [2]:
a=np.array([[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]])

In [4]:
b=np.linalg.inv(a)
b

array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25, -0.25, -0.25],
       [ 0.25, -0.25,  0.25, -0.25],
       [ 0.25, -0.25, -0.25,  0.25]])

In [6]:
c=np.array([1,2,1,1])
c.shape

(4,)

In [7]:
print(np.dot(b,c))

[ 1.25  0.25 -0.25 -0.25]


In [8]:
a=np.array([[1,1,-1,-1],[2,-1,2,-1],[-1,1,1,0],[0,1,1,1]])
b=np.linalg.inv(a)
c=np.array([[2,0,-2,1],[1,1,1,3],[0,2,1,1],[1,2,2,2]])
print(np.dot(b,c))

[[ 1.00000000e+00  3.33066907e-16  2.22044605e-16  1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  2.22044605e-16  1.00000000e+00]
 [-1.38777878e-17  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16  1.00000000e+00  2.22044605e-16]]


In [1]:
#利用python进行LU分解
#LU分解求Ax=b
#过程：A=LU,LZ=b,Ux=Z
 
import numpy as np
import pandas as pd
from scipy import linalg
 
np.random.seed(2)
def LU_decomposition(A,b):
    n=len(A[0])
    L = np.zeros([n,n])
    U = np.zeros([n, n])
    for i in range(n):
        L[i][i]=1
        if i==0:
            U[0][0] = A[0][0]
            for j in range(1,n):
                U[0][j]=A[0][j]
                L[j][0]=A[j][0]/U[0][0]
        else:
                for j in range(i, n):#U
                    temp=0
                    for k in range(0, i):
                        temp = temp+L[i][k] * U[k][j]
                    U[i][j]=A[i][j]-temp
                for j in range(i+1, n):#L
                    temp = 0
                    for k in range(0, i ):
                        temp = temp + L[j][k] * U[k][i]
                    L[j][i] = (A[j][i] - temp)/U[i][i]
    
    Z=linalg.solve(L, b)
    x=linalg.solve(U, Z)
    
    print("L=",L)
    print("U=",U)
    print("Z=",Z)
    print("Exact solution: x=",x)
    print(np.linalg.inv(L))
    
    return


In [15]:
a=np.array([[2,-1,3],[1,2,1],[2,4,3]])
b=np.array([-3,4,7])
LU_decomposition(a,b)

L= [[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  2.  1. ]]
U= [[ 2.  -1.   3. ]
 [ 0.   2.5 -0.5]
 [ 0.   0.   1. ]]
Z= [-3.   5.5 -1. ]
Exact solution: x= [ 1.  2. -1.]
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [-0.  -2.   1. ]]


In [17]:
#为方便示意不考虑时间空间代价
def Cholesky_plus(matrix):
    w = matrix.shape[0]
    L = np.zeros((w,w))
    for i in range(w):
        L[i,i] = 1
    D = np.zeros((w,w))
    for i in range(w):
        D[i,i] = matrix[i,i] - np.dot(np.dot(L[i,:i],D[:i,:i]),L[i,:i].T)
        for j in range(i+1,w):
            L[j,i] = (matrix[j,i] - np.dot(np.dot(L[j,:i],D[:i,:i]),L[i,:i].T))/D[i,i]
    return L,D

In [18]:
a=np.array([[1,2,1,-3],[2,5,0,-5],[1,0,14,1],[-3,-5,1,15]])
L,D=Cholesky_plus(a)
print(L)
print(D)

[[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [ 1.         -2.          1.          0.        ]
 [-3.          1.          0.66666667  1.        ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 9. 0.]
 [0. 0. 0. 1.]]


In [19]:
b=np.array([1,1,1,1])
LU_decomposition(a,b)

L= [[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [ 1.         -2.          1.          0.        ]
 [-3.          1.          0.66666667  1.        ]]
U= [[ 1.  2.  1. -3.]
 [ 0.  1. -2.  1.]
 [ 0.  0.  9.  6.]
 [ 0.  0.  0.  1.]]
Z= [ 1.         -1.         -2.          6.33333333]
Exact solution: x= [ 56.88888889 -16.22222222  -4.44444444   6.33333333]
[[ 1.         -0.         -0.         -0.        ]
 [-2.          1.         -0.         -0.        ]
 [-5.          2.          1.          0.        ]
 [ 8.33333333 -2.33333333 -0.66666667  1.        ]]


In [20]:
a=np.array([[1/2,0,-1/2,0],[-1/2,0,-1/2,0],[1,1,0,0],[0,0,1,1]])
print(np.linalg.inv(a))

[[ 1. -1.  0.  0.]
 [-1.  1.  1.  0.]
 [-1. -1. -0. -0.]
 [ 1.  1.  0.  1.]]


In [21]:
a=np.array([[1,-1,-2],[1,0,1],[1,1,0]])
print(np.linalg.inv(a))

[[ 0.25  0.5   0.25]
 [-0.25 -0.5   0.75]
 [-0.25  0.5  -0.25]]


In [2]:
a=np.array([[1,0,2,1],[-1,2,1,3],[1,2,5,5],[2,-2,1,-2]])

In [3]:
print(np.linalg.inv(a))

LinAlgError: Singular matrix